### ISSUE TITLE
Critical: Missing "lab1" tag

### ISSUE THREAD

**Issue by martinjonsson01** [HermanForsberg/TDA553-lab1#1]
You have not created a tag on the last commit in the master branch, as you were directed to do in submission instruction 5. 

Please make one. For instructions on creating a tag, see [this link.](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/managing-tags)

**Comment by HermanForsberg** [comment]
It should have been fixed. We just forgot to commit the change

**Comment by martinjonsson01** [comment]
👍
