### ISSUE TITLE
CRITICAL: It is possible to violate a sanity check by calling public methods

### ISSUE THREAD

**Issue by martinjonsson01** [HermanForsberg/TDA553-lab1#10]
You have not encapsulated the `Car` class well enough, so there are methods available to the caller that lets them violate sanity checks.

`setCurrentSpeed` can be used to set `currentSpeed` to a value outside of the allowed interval.
https://github.com/HermanForsberg/TDA553-lab1/blob/c1e8fb95b7f276886b8ac4c06c7853760cccf7cc/src/Car.java#L38

`incrementSpeed` and `decrementSpeed` can be used to do the same. (At least for Saab.)
`incrementSpeed` and `decrementSpeed` can be used to do what is equivalent to calling `gas` and `brake` with values outside of the interval [0, 1].
https://github.com/HermanForsberg/TDA553-lab1/blob/c1e8fb95b7f276886b8ac4c06c7853760cccf7cc/src/Car.java#L70-L72

`setEnginePower` can be used to set a negative engine power and therefore allow `gas` and `brake` to do the opposite of what they should.
https://github.com/HermanForsberg/TDA553-lab1/blob/c1e8fb95b7f276886b8ac4c06c7853760cccf7cc/src/Car.java#L34

**Comment by HermanForsberg** [comment]
Vill du att vi ändrar alla dessa Critical issues och lämnar in som Labb 1 igen? Vi har börjat på labb 2 och redan gjort ganska stora ändringar och även fixat några av issuesen du markerat. Hur ska vi göra i så fall om vi ska lämna in labb 1 igen när vi börjat på labb 2?

**Comment by martinjonsson01** [comment]
Ja, det är meningen att ni ska åtgärda critical issues från labb 1 samtidigt som ni arbetar på labb 2. Det är helt okej att ni inkluderar kod från labb 2 när ni lämnar in lösningar på critical issues från labb 1. Det är bara att åtgärda dem (om ni inte redan gjort det), skapa en ny tagg (lab1b, lab1c, osv...) och sedan be mig ta en titt igen.

**Comment by HermanForsberg** [comment]
Menar du att vi ska göra setCurrentSpeed och setEnginePower till private när du skriver "You have not encapsulated the Car class well enough"?

**Comment by martinjonsson01** [comment]
Javisst, det är ett sätt att lösa det! Anledningen att jag inte säger exakt vad jag vill att ni ska göra är för att vi vill att ni ska förstå själva problemet (i detta fallet att beteenden som inte borde vara möjliga är det), och förstå vad lösningen är och varför det är en lösning. 

Det grundläggande problemet här är att inkapslingen för Car är bristfällig, och ett sätt att lösa detta är genom att dölja metoderna.

**Comment by HermanForsberg** [comment]
Vi har nu gjort en tag "Lab1b" där vi fixat alla de Critical issuesen och de flesta av de andra issuesen!

**Comment by martinjonsson01** [comment]
Den här issue:n är fortfarande inte löst, då ni har gjort dessa metoder public:
https://github.com/HermanForsberg/TDA553-lab1/blob/610d3c7a0a9e9982ad84cfef74d5cf5c7634d6dc/src/Car.java#L65-L73

Nu går det att bryta en sanity check: "gas() and brake() only accept values in the interval [0,1]" genom att anropa `incrementSpeed(1.1d)`, till exempel. Det är tekniskt sett inte  `gas` som anropas, men eftersom allt den metoden gör i praktiken är delegerar vidare till `incrementSpeed` så har ni gjort det möjligt för användaren att kringgå kravet på att input ska vara i intervallet [0, 1].

**Comment by HermanForsberg** [comment]
Vi har nu satt Lab1c som en tag där vi löst detta problem och de nya du la till. Dessutom ska vi ha lagt till mer i reflektionen

**Comment by martinjonsson01** [comment]
Snyggt, bra jobbat! 👍
