### ISSUE TITLE
Use more informative commit messages

### ISSUE THREAD

**Issue by martinjonsson01** [HermanForsberg/TDA553-lab1#12]
It is important to get into the habit of writing clear and meaningful commit messages. Things like "fixed stuff" or "Done for the day" have little to no meaning to any future person looking at what you have done. 

Instead, try to describe what you have done in the commit. Something like "Resolved bug involving incorrect date format" or "Implemented support for .yaml configuration files". 

["Speed"](https://github.com/HermanForsberg/TDA553-lab1/commit/eb78e4a75989474a484db6004d80f108b513dc8e)

["Volvo"](https://github.com/HermanForsberg/TDA553-lab1/commit/25c3c7ec6570e30143574385a49ee4990407cc70)

["Mer tester"](https://github.com/HermanForsberg/TDA553-lab1/commit/9dccac9c19da0bf47db9541198e1c399d28f08e8)

**Comment by HugoUnosson** [comment]
Noted
