### ISSUE TITLE
CRITICAL: Duplicated code

### ISSUE THREAD

**Issue by martinjonsson01** [HermanForsberg/TDA553-lab1#20]
You have duplicated code between CarRepairShop and CarTransport. 

There are slight variations, like under what conditions a car can be loaded, but most of it is duplicated. Try using delegation in order to eliminate this duplicated code.

https://github.com/HermanForsberg/TDA553-lab1/blob/23b90c2c9330a0c78920183b6143f1bfaadc5c22/src/carRepairShop/CarRepairShop.java#L30-L52
https://github.com/HermanForsberg/TDA553-lab1/blob/23b90c2c9330a0c78920183b6143f1bfaadc5c22/src/vehicle/CarTransport.java#L46-L69

**Comment by HermanForsberg** [comment]
we have now made a lab2b tag for our fixes

**Comment by martinjonsson01** [comment]
Nicely done! 

Also, these if-statements are a bit strangely formatted
https://github.com/HermanForsberg/TDA553-lab1/blob/317ffc3fce39eeb6b1c1b886f6bf64d65a6cb261/src/vehicle/CarTransport.java#L43-L55
you can write them simpler like so:
```java
    public void load(Car car) { //You can only load cars.
        if (load.distanceToCar(car, getX(), getY()) < 1 && 
            !flatbed.getFlatbedUp()) {
            load.load(car);
        }
    }

    public void unload(Car car) { //You can only load cars.
        if (!flatbed.getFlatbedUp()) {
            load.unload(car);
        }
    }
```
