### ISSUE TITLE
CRITICAL: Incorrect understanding of Liskov Substitution Principle

### ISSUE THREAD

**Issue by martinjonsson01** [HermanForsberg/TDA553-lab1#22]
https://github.com/HermanForsberg/TDA553-lab1/blob/23b90c2c9330a0c78920183b6143f1bfaadc5c22/src/reflections/lab2reflection.txt#L1-L7

If the contract in Vehicle is "if you give me a double between 0 and 1 i will increment the speed of the vehicle" then you're breaking that contract here:

https://github.com/HermanForsberg/TDA553-lab1/blob/23b90c2c9330a0c78920183b6143f1bfaadc5c22/src/vehicle/CarTransport.java#L27-L32
https://github.com/HermanForsberg/TDA553-lab1/blob/23b90c2c9330a0c78920183b6143f1bfaadc5c22/src/vehicle/Scania.java#L21-L26

Reconsider whether or not you're breaking LSP currently. And if you come to the conclusion that you are, can you find a way to make your design follow the LSP? (Hint: This does not involve changing the code at all.)

**Comment by AronLundh** [comment]
Forgot to add "fixed issue 22" in the commit message. The commit message was something like "fixed the contract in lab2reflection"
