### ISSUE TITLE
Encapsulation: Make this method private

### ISSUE THREAD

**Issue by martinjonsson01** [HermanForsberg/TDA553-lab1#4]
The speed factor is an implementation detail which should not be visible from outside the class.

https://github.com/HermanForsberg/TDA553-lab1/blob/c1e8fb95b7f276886b8ac4c06c7853760cccf7cc/src/Saab95.java#L20-L24

https://github.com/HermanForsberg/TDA553-lab1/blob/c1e8fb95b7f276886b8ac4c06c7853760cccf7cc/src/Volvo240.java#L12-L14

**Comment by AronLundh** [comment]
When making speedFactor private in Saab and Volvo, we get an error message "Cannot reduce the visibility of the inherited method from Car".

How do we fix this?

**Comment by martinjonsson01** [comment]
It looks like you've made `speedFactor()` an abstract method in `Vehicle`, which means that it can't be private in the subclasses, it has to be protected. Private visibility means that only the containing class can see it, while protected allows for access in the same package and in subclasses.
